services:
  teamcity-server:
    image: 'jetbrains/teamcity-server'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    volumes:
      - 'D:\workshop\teamcity\server\:/data/teamcity_server/datadir'
      - 'D:\workshop\teamcity\logs\:/opt/teamcity/logs'
    ports:
      - 8111:8111
  teamcity-agent:
    image: 'yzhu228/teamcity-agent-hugo'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    volumes:
      - 'D:\workshop\teamcity\agent\:/data/teamcity_agent/conf'
    environment:
      - SERVER_URL=teamcity-server:8111
